apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fin-model
  template:
    metadata:
      labels:
        app: fin-model
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: fin-model-prediction
        image: nueri/fin-pred:latest
        ports:
        - containerPort: 5000
